# site settings
title: OnlineBah
subtitle: Sandakan
email: onlinebah2u@gmail.com
description: Welcome to my website!<br> How can I help you?
baseurl: # the subpath of your site, e.g. /blog work only host in github pages not local
url: "www.onlinebah.com" # the base hostname & protocol for your site
author:
street_address: IJM
city: Sandakan
state: Sabah
zip_code: 90000
country: Malaysia
phone: (+60)183202822

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url: https://www.facebook.com/WebDigitalAgency/
github_url:
gitlab_url:
googleplus_url: 
instagram_url: https://www.instagram.com/onlinebah/?hl=en
linkedin_url: https://www.linkedin.com/in/josiah-soh-01b32729/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/OnlineBah

# build settings
markdown: kramdown

sass:
  style: compressed
